# Exercícios Maratona Data Science - Numpy


Fácil 

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [54]:
import numpy as np
print(np.__version__)

1.15.4


⚫2- Crie uma matriz 1D com números de 0 a 9
Saída desejada:
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x= np.arange(10,)
print(x)
type(x)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’
Saída desejada:
array([[ True, True, True],
[ True, True, True],
[ True, True, True]], dtype=bool)

In [60]:
y = np.array([[ True, True, True], [ True, True, True], [ True, True, True]], dtype=bool)
print(y)
# ou é possível também fazer de outro modo : 
np.full((3, 3), True, dtype=bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

⚫4- Extraia todos os números ímpares de ‘arr’
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Saída desejada: array([1, 3, 5, 7, 9])

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print (arr[1::2])

[1 3 5 7 9]


⚫5- Substitua todos os números ímpares arr por -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Saída desejada: array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [20]:
arr[1::2] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Médio 

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Saída desejada: array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
arr == array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr =np.arange(10,)
print(arr)
x = arr
print(x)
x[1::2]= -1 
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:
np.arange(10)
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Saída desejada:
array([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]])

In [61]:
matriz = np.arange(10,)
print(matriz)
matriz.reshape(2, -1) # Setando para “-1” o número de colunas é decidido automáticamente!


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

⚫3- Empilhe matrizes verticalmente:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Saída desejada:
array([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9],
[1, 1, 1, 1, 1],
[1, 1, 1, 1, 1]])

In [69]:
a = np.arange(10).reshape(2,-1)
print(a)
b = np.repeat(1, 10).reshape(2,-1)
print(b)

np.vstack([a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

⚫4- Empilhe as matrizes horizontalmente:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Saída desejada:
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [124]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.
a = np.array([1,2,3])
Saída desejada: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [127]:
import numpy as np
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])